Add Global Energy Monitor data to powerplant matching
PyPSA/powerplantmatching pull request #79
Opened 2022-11-01 16:50 UTC by pz-max

Closes https://github.com/PyPSA/powerplantmatching/issues/76

## Change proposed in this Pull Request

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other

## Checklist

- [ ] I have added a note to release notes `doc/release_notes.rst`.
- [ ] I have used `pre-commit run --all` to lint/format/check my contribution
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have adjusted the docstrings in the code appropriately.

2022-11-01 16:59 UTC, pz-max commented
@FabianHofmann now we have a PR. This PR adds coal power plants from GEM. I am happy to contribute an interface to tracked gas power plants. Open questions:

- How can I test if the interface works?
- Some information/ test if the power plant coverage improves would also be helpful. Obviously, this is country-specific. Thinking big, a test of how for each country the data coverage improves would be great. This might be out of our scope for us atm., but I am sure someone might be interested to contribute that in future. Maybe we should track that as feature request?

Happy to meet and discuss the above questions. Here my booking link: https://calendly.com/pypsa-meets-earth/pypsa-meets-earth-exchange-30min

2022-11-02 08:23 UTC, FabianHofmann requested changes
Thanks @pz-max this look good. After that small style correction we can merge it.

2022-11-02 08:23 UTC, FabianHofmann commented on powerplantmatching/data.py
> +    ]
```suggestion
    df = df[df.Status.isin(["operating", "mothballed", "construction"]) 
```

2022-11-02 23:07 UTC, pz-max commented
@FabianHofmann ready to merge.
However, if you have some time we could test it together before the merge.
If I remember correctly the matching stuff did not work well...

2022-11-03 07:24 UTC, FabianHofmann approved these changes

2022-11-03 07:27 UTC, FabianHofmann commented
thanks @pz-max, I think we can merge first and if there is still problems with the merging, we can tackle it together.

2022-11-03 07:27 UTC, merged